"""Module modul._version — minimal module docstring."""

# file generated by setuptools-scm
# don't change, don't track in version control
# Pylint: this file is auto-generated and uses names that don't follow
# the project's naming conventions; disable the invalid-name check here.
# pylint: disable=invalid-name

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = '0.24.1.dev21'
__version_tuple__ = version_tuple = (0, 24, 1, 'dev21')

__commit_id__ = commit_id = 'gbe89315a4'
