"""Module modul._version — minimal module docstring."""

# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "VERSION",
    "version_tuple",
    "__commit_id__",
    "COMMIT_ID",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union

    VersionTuple = Tuple[Union[int, str], ...]
    CommitId = Union[str, None]
else:
    VersionTuple = object
    CommitId = object

VERSION: str
__version__: str
__version_tuple__: VersionTuple
version_tuple: VersionTuple
COMMIT_ID: CommitId
__commit_id__: CommitId

# Public names are the uppercase constants (`VERSION`, `COMMIT_ID`).
# The dunder names (`__version__`, `__commit_id__`) are kept as
# legacy aliases for backwards compatibility.
__version__ = VERSION = '0.24.1.dev49'
__version_tuple__ = version_tuple = (0, 24, 1, 'dev49')

__commit_id__ = COMMIT_ID = 'gb2e481b8f'
