# file generated by update_version.py from VERSION file
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "VERSION",
    "version_tuple",
    "__commit_id__",
    "COMMIT_ID",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union

    VersionTuple = Tuple[Union[int, str], ...]
    CommitId = Union[str, None]
else:
    VersionTuple = object
    CommitId = object

VERSION: str
__version__: str
__version_tuple__: VersionTuple
version_tuple: VersionTuple
COMMIT_ID: CommitId
__commit_id__: CommitId

# Provide both uppercase constants and lowercase/dunder aliases for
# backwards compatibility so tools that regenerate this file don't
# remove either form.
__version__ = VERSION = version = '0.24.0'
__version_tuple__ = version_tuple = (0, 24, 0)

__commit_id__ = COMMIT_ID = None
