import random
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_VERTICES = 12
ASTEROID_IRREGULARITY = 0.4
PLAYER_RADIUS = 25
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 160
PLAYER_ACCELERATION = 300
PLAYER_MAX_SPEED = 400
PLAYER_FRICTION = 0.02
PLAYER_ROTATION_SPEED = 180
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
SHOT_RADIUS = 5
SCORE_LARGE = 20
SCORE_MEDIUM = 50
SCORE_SMALL = 100
PLAYER_LIVES = 3
INVINCIBILITY_TIME = 3.0
RESPAWN_POSITION_X = SCREEN_WIDTH / 2
RESPAWN_POSITION_Y = SCREEN_HEIGHT / 2
EXPLOSION_PARTICLES = 15
PARTICLE_COLORS = ["white", "yellow", "red"]
STAR_COUNT = 100
STAR_SIZES = [1, 2, 3]
STAR_COLORS = ["white", "lightblue", "yellow"]
COLLISION_DEBUG = False

POWERUP_RADIUS = 15
POWERUP_SPAWN_CHANCE = 0.3
POWERUP_MAX_COUNT = 3
POWERUP_LIFETIME = 15.0
SHIELD_DURATION = 3.0
POWERUP_TYPES = ["shield", "triple_shot", "rapid_fire",
                 "laser_weapon", "missile_weapon", "shotgun_weapon"]
POWERUP_COLORS = {
    "shield": "blue",
    "triple_shot": "magenta",
    "rapid_fire": "yellow",
    "laser_weapon": "green",
    "missile_weapon": "red",
    "shotgun_weapon": "orange",
}
RAPID_FIRE_COOLDOWN = 0.1
RAPID_FIRE_DURATION = 8.0
TRIPLE_SHOT_DURATION = 10.0

HIGHSCORE_FILE = "highscores.json"
HIGHSCORE_MAX_ENTRIES = 10
HIGHSCORE_NAME_LENGTH = 3
HIGHSCORE_DEFAULT_NAME = "ABC"
HIGHSCORE_ALLOWED_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

MENU_TITLE_FONT_SIZE = 72
MENU_ITEM_FONT_SIZE = 36
MENU_SELECTED_COLOR = "yellow"
MENU_UNSELECTED_COLOR = "white"
MENU_TITLE_COLOR = "cyan"
MENU_ITEM_SPACING = 50
MENU_TRANSITION_SPEED = 0.5
MENU_BACKGROUND_ALPHA = 180

MENU_BUTTON_WIDTH = 300
MENU_BUTTON_HEIGHT = 50
MENU_BUTTON_PADDING = 10
MENU_BUTTON_RADIUS = 5
MENU_FADE_SPEED = 2.0

DIFFICULTY_EASY_ASTEROIDS = 3
DIFFICULTY_NORMAL_ASTEROIDS = 5
DIFFICULTY_HARD_ASTEROIDS = 8

DIFFICULTY_EASY_INTERVAL = 8.0
DIFFICULTY_NORMAL_INTERVAL = 5.0
DIFFICULTY_HARD_INTERVAL = 3.0

ARCADE_MODE_TIME = 180
ARCADE_MODE_BONUS_TIME = 5

CREDITS_MASTERMIND = "Ajimaru"
CREDITS_TITLE = "CREDITS"
CREDITS_GAME_NAME = "AJITROIDS"
CREDITS_DEVELOPER = "GitHub Copilot"
CREDITS_GRAPHICS = "GitHub Copilot"
CREDITS_SOUND = "Command Line"
CREDITS_SPECIAL_THANKS = [
    "Boot.dev for the Python-Tutorials",
    "Pygame Community for the awesome library",
]

CREDITS_SCROLL_SPEED = 50
CREDITS_LINE_SPACING = 40
CREDITS_WEBSITE = "https://ajimaru.github.io"

POINTS_PER_LEVEL = 2500
MAX_LEVEL = 666
LEVEL_UP_DISPLAY_TIME = 1.5
BASE_ASTEROID_COUNT = 3
BASE_SPAWN_INTERVAL = 5.0
ASTEROID_COUNT_PER_LEVEL = 1
SPAWN_INTERVAL_REDUCTION = 0.4

WEAPON_STANDARD = "standard"
WEAPON_LASER = "laser"
WEAPON_MISSILE = "missile"
WEAPON_SHOTGUN = "shotgun"

WEAPON_COLORS = {WEAPON_STANDARD: "white", WEAPON_LASER: "green",
                 WEAPON_MISSILE: "red", WEAPON_SHOTGUN: "orange"}

LASER_AMMO = 15
MISSILE_AMMO = 8
SHOTGUN_AMMO = 12

BOSS_LEVEL_INTERVAL = 10
BOSS_RADIUS = 50
BOSS_COLOR = (128, 0, 128)
BOSS_BASE_HEALTH = 20
BOSS_HEALTH_PER_LEVEL = 10
BOSS_MOVE_SPEED = 70
BOSS_ATTACK_INTERVAL = 2.0
BOSS_DEATH_DURATION = 3.0
BOSS_SCORE = 500

BOSS_PROJECTILE_RADIUS = 8
BOSS_PROJECTILE_SPEED = 200
BOSS_PROJECTILE_COLORS = {"normal": (200, 0, 200), "homing": (
    255, 0, 0), "explosive": (255, 128, 0)}


def generate_default_highscores():
    allowed_chars = HIGHSCORE_ALLOWED_CHARS
    max_entries = HIGHSCORE_MAX_ENTRIES
    name_length = HIGHSCORE_NAME_LENGTH

    highscores = []
    for i in range(max_entries):
        name = "".join(random.choice(allowed_chars)
                       for _ in range(name_length))
        score = (max_entries - i) * 1000
        highscores.append({"name": name, "score": score})

    return highscores


DEFAULT_HIGHSCORES = generate_default_highscores()
