#!/usr/bin/env python3

"""Update _version.py and pyproject.toml from VERSION file

This script ensures the version is only maintained in one place (VERSION file)
and automatically updates:
1. modul/_version.py - for runtime version display
2. pyproject.toml - fallback_version for setuptools-scm
"""

import re
from pathlib import Path

# Read VERSION file (repo root)
version_file = Path(__file__).parent.parent / "VERSION"
version = version_file.read_text().strip()

# Parse version into tuple
version_parts = re.match(r'^(\d+)\.(\d+)\.(\d+)(?:\.(.+))?$', version)
if version_parts:
    major, minor, patch, dev = version_parts.groups()
    if dev:
        VERSION_TUPLE = f"({major}, {minor}, {patch}, '{dev}')"
    else:
        VERSION_TUPLE = f"({major}, {minor}, {patch})"
else:
    raise ValueError(f"Invalid version format: {version}")

# Update modul/_version.py
version_py = Path(__file__).parent / "_version.py"
version_py_content = f'''# file generated by update_version.py from VERSION file
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "VERSION",
    "version_tuple",
    "__commit_id__",
    "COMMIT_ID",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union

    VersionTuple = Tuple[Union[int, str], ...]
    CommitId = Union[str, None]
else:
    VersionTuple = object
    CommitId = object

VERSION: str
__version__: str
__version_tuple__: VersionTuple
version_tuple: VersionTuple
COMMIT_ID: CommitId
__commit_id__: CommitId

# Provide both uppercase constants and lowercase/dunder aliases for
# backwards compatibility so tools that regenerate this file don't
# remove either form.
__version__ = VERSION = version = '{version}'
__version_tuple__ = version_tuple = {VERSION_TUPLE}

__commit_id__ = COMMIT_ID = None
'''

version_py.write_text(version_py_content)
print(f"✓ Updated modul/_version.py to version {version}")

# Update pyproject.toml fallback_version
pyproject = Path(__file__).parent.parent / "pyproject.toml"
pyproject_content = pyproject.read_text()

# Replace fallback_version line
pyproject_content = re.sub(
    r'fallback_version\s*=\s*"[^"]*"',
    f'fallback_version = "{version}"',
    pyproject_content
)

pyproject.write_text(pyproject_content)
print(f"✓ Updated pyproject.toml fallback_version to {version}")
print(f"\n✅ Version successfully updated to {version}")
print("   Next steps:")
print("   1. git add VERSION modul/_version.py pyproject.toml")
print(f"   2. git commit -m 'version bump to {version}'")
