#!/usr/bin/env python3
"""Update _version.py and pyproject.toml from VERSION file

This script ensures the version is only maintained in one place (VERSION file)
and automatically updates:
1. modul/_version.py - for runtime version display
2. pyproject.toml - fallback_version for setuptools-scm
"""

import re
from pathlib import Path

# Read VERSION file
version_file = Path(__file__).parent / "VERSION"
version = version_file.read_text().strip()

# Parse version into tuple
version_parts = re.match(r'^(\d+)\.(\d+)\.(\d+)(?:\.(.+))?$', version)
if version_parts:
    major, minor, patch, dev = version_parts.groups()
    if dev:
        version_tuple = f"({major}, {minor}, {patch}, '{dev}')"
    else:
        version_tuple = f"({major}, {minor}, {patch})"
else:
    raise ValueError(f"Invalid version format: {version}")

# Update modul/_version.py
version_py = Path(__file__).parent / "modul" / "_version.py"
version_py_content = f'''# file generated by update_version.py from VERSION file
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = '{version}'
__version_tuple__ = version_tuple = {version_tuple}

__commit_id__ = commit_id = None
'''

version_py.write_text(version_py_content)
print(f"✓ Updated modul/_version.py to version {version}")

# Update pyproject.toml fallback_version
pyproject = Path(__file__).parent / "pyproject.toml"
pyproject_content = pyproject.read_text()

# Replace fallback_version line
pyproject_content = re.sub(
    r'fallback_version\s*=\s*"[^"]*"',
    f'fallback_version = "{version}"',
    pyproject_content
)

pyproject.write_text(pyproject_content)
print(f"✓ Updated pyproject.toml fallback_version to {version}")
print(f"\n✅ Version successfully updated to {version}")
print(f"   Next steps:")
print(f"   1. git add VERSION modul/_version.py pyproject.toml")
print(f"   2. git commit -m 'version bump to {version}'")

